swagger: "2.0"
info:
  version: "0.0.1"
  title: Todo List Api
# during dev, should point to your local machine
host: localhost:3001
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /tasks:
    x-swagger-router-controller: task
    get:
      description: display a list of all tasks
      operationId: index
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ListResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    x-swagger-router-controller: task
    post:
      consumes:
        - application/json
      produces:
        - application/json
        - text/xml
        - text/html
      description: Create a new task
      operationId: create
      parameters:
        - name: month
          in: query
          description: month
          required: false
          type: integer
        - name: day
          in: query
          description: day
          required: false
          type: integer
        - name: year
          in: query
          description: year
          required: false
          type: integer
        - name: description
          in: query
          description: description
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ObjectResponse"
        "400":
          description: Success
          schema:
            $ref: "#/definitions/ObjectResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ObjectResponse"
  /task/{id}:
    x-swagger-router-controller: task
    delete:
      description: Delete a specific task
      operationId: destroy
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ObjectResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    x-swagger-router-controller: task
    put:
      description: Update a specific task
      operationId: update
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ObjectResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
# complex objects have schema definitions
definitions:
  ObjectResponse:
    type: object
  ListResponse:
    type: array
    items: 
      type: object
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    type: object
    required:
      - message
    properties:
      message:
        type: string
